server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.30:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Wentiliangkaihua@hz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    root: info
